name: CD - Deploy academy Vite App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
      - name: Set lowercase owner name
        id: lowercase
        run: |
            echo "REPO_OWNER_LOWER=$(echo '${{ env.REPO_OWNER }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.REPO_OWNER_LOWER }}/academy-vite-app:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ env.REPO_OWNER_LOWER }}/academy-vite-app:latest

      - name: SSH into server & deploy container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ env.REPO_OWNER_LOWER }} --password-stdin
            docker pull ghcr.io/${{ env.REPO_OWNER_LOWER }}/academy-vite-app:latest
            docker stop academy-vite-app || true
            docker rm academy-vite-app || true
            docker run -d --name academy-vite-app -p 5173:80 ghcr.io/${{ env.REPO_OWNER_LOWER }}/academy-vite-app:latest
